### ISSUE TITLE
“ChangeDresser.ApparelStorageLabel”could not be applied in game. 

### ISSUE THREAD

**Issue by VaniatD** [KiameV/rimworld-changedresser#1]
![20170316002011](https://cloud.githubusercontent.com/assets/26436338/23958940/ab717cae-09de-11e7-8a6f-f9f71025731f.png)
like this.

**Comment by KiameV** [comment]
Working on this and fixing "Edit" not showing up on the Apparel Group options drop down.

**Comment by KiameV** [comment]
Fix is in. Also I missed in the English version the text for "ChangeDresser.EditApparelGroup" which is just "Edit". Nothing else changed in there.

Thanks for reporting this!
