### ISSUE TITLE
Items lose their Forced status when visiting the change dresser

### ISSUE THREAD

**Issue by bonesbro** [KiameV/rimworld-changedresser#16]
If a pawn has an item that is Forced, and they visit the change dresser to swap gear, the forced items lose their Forced status.  Interestingly, those items are NOT replaced that visit, even if a better one exists, but they will be replaced next visit.

**Setup:**  (the item types are arbitrary)

- Have at least two shirts, one of which is significantly better than the other.  Put the better one in the dresser and force-equip the crappy shirt.
- Have at least one pair of pants stored in the dresser.

**Repro steps:**

1. Have the pawn unequip their pants.  They will drop the pants then gain the job "Equipping wooden change dresser".
2. When they reach the dresser and put on the stored pants, their crappy shirt will no longer be Forced, but they will still be wearing it.
3. Toggle draft on the colonist.  They will switch to the good shirt from storage.

Variants:
- If you toggle draft after setup or after step 1, nothing unexpected happens.  The crappy shirt stays Forced and stays equipped.
- If you give the colonist another job after step 2, they will then run over to change again and will also replace their crappy shirt.

**Comment by KiameV** [comment]
Fixed with latest commit. Thanks!
