### ISSUE TITLE
[BUG] Trading drops won't be picked up again by the Change Dresser.

### ISSUE THREAD

**Issue by frenchiveruti** [KiameV/rimworld-changedresser#22]
So, I've reported this on forum but I think it's better here for a track on progress and also because I'll attach a video here.
The issue remains the same. Smokebelts and ShieldBelts won't get picked up again after a trade is performed.

I hope the video here is enough for a report:
https://www.youtube.com/watch?v=ToN-uAAAC-g

**Comment by KiameV** [comment]
Belts will now be picked up
