### ISSUE TITLE
[Bug] Clothing duplication bug.

### ISSUE THREAD

**Issue by frenchiveruti** [KiameV/rimworld-changedresser#23]
I keep getting this red error messages stating that there are duped items around.
I erased them manually but they came back in.
(It may be linked on "forcing" clothes on colonist and then drafting them)
Log:
[Error Log duplication bug.txt](https://github.com/KiameV/rimworld-changedresser/files/1549308/Error.Log.duplication.bug.txt)

On the end, there's a map corruption maybe related to it?
Tell me if you need other mods in the list.
Thanks

**Comment by KiameV** [comment]
Hopefully this has been fixed with the newest update.

Leaving open for now
