### ISSUE TITLE
[BUG] Change Dresser breaks GUI if used with Rock5 Butchers can count meat.

### ISSUE THREAD

**Issue by frenchiveruti** [KiameV/rimworld-changedresser#24]
Check this forum post:
https://ludeon.com/forums/index.php?topic=37177.msg385488#msg385488
Also this Github Issue:
https://github.com/Rock5/ButchersCanCountMeat/issues/1

I think there's some patching somewhere that makes conflicts with the GUI.

**Comment by frenchiveruti** [comment]
Steps to reproduce:
(Use god mode in dev mode)
1. Place a Butcher table with both mods installed.
2. Create a Bill that "butchers meat until X amount".
3. Place a **Weapon storage** or a **Change Dresser** anywhere, don't do anything else with them.
4. Go back into the butcher table and you'll see the GUI flashes and breaks, if you open any other menu it will appear broken as in the attached image.
5. Deselect the butcher table, GUI goes back to normal.
6. Remove **Both** storage items, GUI works again as intended.

**Comment by KiameV** [comment]
Fixed. Thanks for reporting this issue.
