### ISSUE TITLE
[Bug] Traders sometimes won't open trading screen. (With logs!)

### ISSUE THREAD

**Issue by frenchiveruti** [KiameV/rimworld-changedresser#25]
So, I don't know what causes this issue so no real easy reproduce steps, but from time to time, a trader won't open the trade screen, unless I save and then load the game again.
Not a big bug but it's kind of annoying.
Here's the logfile:
[Bug.txt](https://github.com/KiameV/rimworld-changedresser/files/1566045/Bug.txt)

**Comment by KiameV** [comment]
Should be fixed with either the current version or beta B18 version.
