### ISSUE TITLE
Need keyed

### ISSUE THREAD

**Issue by VaniatD** [KiameV/rimworld-changedresser#3]
![qq 20170324142037](https://cloud.githubusercontent.com/assets/26436338/24282970/ced21c92-109d-11e7-85f4-a9be1eb8f5ef.png)

**Comment by KiameV** [comment]
Doh indeed. I'll get an update out shortly

Thanks for submitting this defect VaniatD

**Comment by KiameV** [comment]
Pushed to steam and committed here.
The new tags are:
	
	<ChangeDresser.StoragePriority>Storage Priority</ChangeDresser.StoragePriority>
	<ChangeDresser.ApparelCount>Pieces of Apparel</ChangeDresser.ApparelCount>
	<ChangeDresser.ApparelGroupCount>Apparel Groups</ChangeDresser.ApparelGroupCount>

I've added these three tags to the two Chinese files as well.

The value for the Storage Priority - Low/Normal/Important/etc - will be supported as all other priority values in the game using the translations in **Core/Languages/<language>/keyed/Enums.xml** tags **<StoragePriority______>**
