### ISSUE TITLE
When I try to uninstall change dresser,if it has some apparels will report errors.

### ISSUE THREAD

**Issue by VaniatD** [KiameV/rimworld-changedresser#6]
Dropped Apparel_Duster736060 in a null map.
Verse.Log:Error(String)
Verse.GenDrop:TryDropSpawn(Thing, IntVec3, Map, ThingPlaceMode, Thing&, Action`2)
RimWorld.GenThing:TryDropAndSetForbidden(Thing, IntVec3, Map, ThingPlaceMode, Thing&, Boolean)
ChangeDresser.Building_Dresser:DropApparel(Apparel, Boolean)
ChangeDresser.Building_Dresser:DropApparel(List`1)
ChangeDresser.Building_Dresser:Dispose()
ChangeDresser.Building_Dresser:DeSpawn()
Verse.ThingContainer:TryAdd(Thing, Boolean)
RimWorld.MinifiedThing:set_InnerThing(Thing)
RimWorld.MinifyUtility:MakeMinified(Thing)
RimWorld.MinifyUtility:Uninstall(Thing)
RimWorld.Designator_Uninstall:DesignateThing(Thing)
RimWorld.<DrawInspectGizmoGridFor>c__AnonStorey3CC:<>m__56F()
Verse.Command_Action:ProcessInput(Event)
Verse.GizmoGridDrawer:DrawGizmoGrid(IEnumerable`1, Single, Gizmo&)
RimWorld.InspectGizmoGrid:DrawInspectGizmoGridFor(IEnumerable`1)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos()
RimWorld.InspectPaneUtility:ExtraOnGUI(IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI()
Verse.WindowStack:WindowStackOnGUI()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

Tried to spawn thing Apparel_Duster736060, but the map provided does not exist.
Verse.Log:Error(String)
Verse.Thing:SpawnSetup(Map)
Verse.ThingWithComps:SpawnSetup(Map)
ChangeDresser.Building_Dresser:DropApparel(Apparel, Boolean)
ChangeDresser.Building_Dresser:DropApparel(List`1)
ChangeDresser.Building_Dresser:Dispose()
ChangeDresser.Building_Dresser:DeSpawn()
Verse.ThingContainer:TryAdd(Thing, Boolean)
RimWorld.MinifiedThing:set_InnerThing(Thing)
RimWorld.MinifyUtility:MakeMinified(Thing)
RimWorld.MinifyUtility:Uninstall(Thing)
RimWorld.Designator_Uninstall:DesignateThing(Thing)
RimWorld.<DrawInspectGizmoGridFor>c__AnonStorey3CC:<>m__56F()
Verse.Command_Action:ProcessInput(Event)
Verse.GizmoGridDrawer:DrawGizmoGrid(IEnumerable`1, Single, Gizmo&)
RimWorld.InspectGizmoGrid:DrawInspectGizmoGridFor(IEnumerable`1)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos()
RimWorld.InspectPaneUtility:ExtraOnGUI(IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI()
Verse.WindowStack:WindowStackOnGUI()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

**Comment by VaniatD** [comment]
Maybe you can drop apparels like _Tool:Try place near thing_ in debug mode.

**Comment by KiameV** [comment]
Fixed for both A17 and A16 in the newest release
